### ISSUE TITLE
[DEBT] Use "I" as a prefix for interface name

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed#350]
## Informations

Type | Version
---|---
Debt | 4.x -> 5.x

****

## Description

Currently, all interfaces in Ts.ED doesn't follow the rule. Now the convention name for the Interface is to use the prefix "I".

To not break the legacy code, we can use that:

```typescript
// new interface
export interface IName {
   ....
}
// legacy interface
/**
 * @deprecated Use IName insteadof
 */
export interface Name extends IName {}
``` 

## Todos

- [ ] Add "I" prefix on interface,
- [ ] Deprecate the legacy interface, 
- [ ] Replace the legacy interface in the Ts.ED code by the new interface,
- [ ] In the next major version, remove all deprecated interface.

**Comment by milewski** [comment]
wait... i thought the `I` was supposed to replace the need for `Interface` in the name... so if its to follow the `I` convention it should be `IName` instead of `INameInterface`

**Comment by Romakita** [comment]
Yes sorry ;)
