### ISSUE TITLE
[EPIC] Release v6

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed#619]
## Information

- **Version:** 6.x
- **Type:** EPIC

## Stories

- [x] Remove all deprecated methods (#620),
- [x] Platform abstraction (#621):
   - [x] API to develop platform adaptation,
   - [x] Express.js v4
   - [x] Koa (PR merged https://github.com/TypedProject/tsed/pull/924)
- [x] Exception Filter (replace GlobalErrorHandlerMiddleware)
- [x] Add @tsed/schema and @tsed/json-mapper (https://github.com/TypedProject/tsed/blob/feat-schema-json-mapper)
- [x] Deprecate ServerLoader, ServerSettings, etc...
- [x] Ts.ED CLI v2
- [x] Update documentation and examples.

## Optional stories for v6

- [ ] Async custom Ajv validator (https://github.com/TypedProject/tsed/issues/698)
- [ ] Http2 support (https://github.com/TypedProject/tsed/issues/929)
- [ ] Platform abstraction (#621):
   - [ ] Express.js v5 (https://github.com/TypedProject/tsed/issues/931)
   - [ ] Fastify (https://github.com/TypedProject/tsed/issues/932)
   - [ ] Hapi
- [ ] Use @tsed/schema and @tsed/ajv to validate Type-graphql models (https://github.com/TypedProject/tsed/issues/930)
- [ ] Support serialization group (@tsed/json-mapper) (https://github.com/TypedProject/tsed/issues/808)

**Comment by chiqui3d** [comment]
Hello @Romakita 
if you will deprecate  `@ServerSettings` then as we will configure all parameters like `mount`

Thanks

**Comment by Romakita** [comment]
Hello @chiqui3d 
ServerSettings will be replaced by an equivalent decorator with the same options and mechanism. 

I want to introduce a new decorator which can be use over any class to store a part of the configuration like @Configuration decorator. DI will resolve configuration when app is built by PlatformFactory.

Currently all stories aren’t described. I’ll doing that this week and see your feedback ;)

See you

**Comment by dlinx** [comment]
@Romakita 
Will there be any support for `5.x` after `6.x` release?

**Comment by Romakita** [comment]
@dlinx
I'll produce a migration page to help developer. A large part of the existing code in v5 will be available on v6. Some v6 features are already available in v5. 
The breaking change will be about existing deprecated features in v5:
- Filters (replaced by the Pipe)
- Converter the signature of the ArrayConverter, etc... will be me simplified. Most projects do not use this feature to change the json mapping behavior.
- To use express a new package will be introduced @tsed/plaftorm-express. Is same thing for koa with @tsed/platform-koa. The server declaration will change but isn't a big change. Migration documention will explain the differences :)

v6 depreciation:
- ConverterService will be deprecated in favor of the @tsed/json-mapper package.
-  Some JsonSchema decorator in v5 will be deprecated in favor of @tsed/schema package.

**Comment by Romakita** [comment]
https://v6.tsed.io (alpha)

**Comment by Romakita** [comment]
Koa integration is almost done. Some internal small changes are necessary to use Koa with the existing code but globally it works. I planed also to support Express v5 by releasing @tsed/platform-express5, just for fun. Then I want to develop a package to support fastisfy. I still have questions for HAPI. Maybe one of you will do it before me :)

**Comment by Romakita** [comment]
Alpha support koa now. The beta will be out soon.

**Comment by Romakita** [comment]
V6 is released 🥳🥳
